feat: added first driver example
connektica/public-code-examples pull request #2
Opened 2024-06-10 14:40 UTC by alexfournierahizoune

### Type
- [X] New feature
- [ ] Refactoring
- [ ] Bug-fix
- [ ] DevOps
- [ ] Testing

### Description
Added driver code example as part of [HOR-852](https://linear.app/connektica/issue/HOR-852/[doc]-add-complex-examples-for-worker-task-doc)
[Source](https://github.com/QCoherence/python_drivers/blob/master/ZNB20.py)

2024-06-12 14:58 UTC, jmdeschenes requested changes
This example if for python 2
How did you test this?

2024-06-12 14:58 UTC, jmdeschenes commented on examples/drivers/ZNB20.py
> +import qt
Unless I misunderstand, qt is one heck of a big library to import. Why do we need this?

2024-06-12 14:58 UTC, jmdeschenes commented on examples/drivers/ZNB20.py
> +            address (string) : TCPIP/GPIB address
An example of how that string should look like would be great.

2024-06-12 14:58 UTC, jmdeschenes commented on examples/drivers/ZNB20.py
> +from instrument import Instrument
how does that work? What do you need installed to make this work?

2024-06-12 14:58 UTC, jmdeschenes commented on examples/drivers/ZNB20.py
> +import logging
imports order:

builtin

external packages

inner packages

```
import types
import logging

import numpy as np
from numpy import pi
```

2024-06-12 14:58 UTC, jmdeschenes commented on examples/drivers/ZNB20.py
> +                print'error in setting start frequency at %s' %startfrequency
How does that work? Is this a python snippet?

2024-06-12 14:58 UTC, jmdeschenes commented on examples/drivers/ZNB20.py
> +            qt.msleep(0.1)
Only place where we use the package. Can we replace it with `time.sleep`?

2024-06-17 17:52 UTC, alexfournierahizoune commented
@jmdeschenes this code example is not and will not be used anywhere, it's only to showcase how to port it to our "framework". It's linked in the worker tasks documentation. I only grabbed the code from a github repo to use as reference.

2024-06-18 18:06 UTC, jmdeschenes approved these changes

2024-06-18 18:09 UTC, merged